services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=elastic
      - POSTGRES_USER=elastic
      - POSTGRES_PASSWORD=elastic
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.27
    environment:
      - discovery.type=single-node
      - node.name=es01
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
    networks:
      - backend

  django:
    build: .
#    volumes:
#      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  data01:
